### ISSUE TITLE
Loading a directory of VCF files fails

### ISSUE THREAD

**Issue by tomwhite** [cloudera/quince#13]
There's a `inputPath.getName().endsWith(".vcf")` check that needs changing.

**Comment by laserson** [comment]
Not obvious to me that the current behavior is incorrect.  If the directory contains multiple VCF files with different headers, the variant loader will probably break.

**Comment by tomwhite** [comment]
You're right. I think ADAM only allows one VCF to be loaded at at time. Quince is consistent with that, so this isn't an issue. Closing.
