### ISSUE TITLE
Enable -variantsonly mode

### ISSUE THREAD

**Issue by laserson** [cloudera/quince#7]
It would be great if we could specify that a VCF file be ingested into a dataset that only has the variant information, and none of the actual genotype calls.

Also, what happens when loading a VCF that contains no genotypes?  (I'm guessing it will deal with it correctly.)

**Comment by laserson** [comment]
@tomwhite, should this be a totally separate CLI tool?  Or just a flag on `LoadVariantsTool`?

**Comment by tomwhite** [comment]
Just a flag.
