### ISSUE TITLE
"FlatVariant" is not actually a Variant, it's a Call

### ISSUE THREAD

**Issue by laserson** [cloudera/quince#9]
The `FlatVariant` object isn't actually a `Variant` but rather a flattened `Call` with some of the `Variant` data denormalized into it.  I suggest renaming `FlatVariant` to `FlatCall`.

**Comment by tomwhite** [comment]
You could argue that's it's possible to look at it the other way round too - as a `Variant` with some of the `Call` data denormalized into it. There is one row per call though. Perhaps it should be `FlatVariantCall`?
